### ISSUE TITLE
Error on chromosomes with just a single SNP

### ISSUE THREAD

**Issue by fgvieira** [veera-dr/ggman#7]
Dear Veera,

I've been trying to use ggman but I'm getting an error:

```
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
  non-numeric argument to binary operator
```

From what I could find out, it seems to give the error on scaffolds with a single SNP. My genome reference is not that good (~1000 scaffolds) and some are quite small and end up having just a single SNP. Would it be possible to allow for these cases?

thanks,

**Comment by drveera** [comment]
Hi,

I'll try to replicate your error and will get back to you. Meanwhile if possible attach a small example data set.

Thanks.

Veera

**Comment by g-pacheco** [comment]
Hello Veera,

Thanks very much for looking into this. I have sent our data to your email (drveeramanikandan@gmail.com). 
Please, let us know should you need any other info.

Your best, George.

**Comment by drveera** [comment]
Hi George,

Thanks for reporting this bug. It was due to a function that calculates the x break points. Now I've fixed it. Re install the package and try again. However, the x axis labels looks messy with >200 chromosomes, even when i put the labels in 90 degree. So you should figure out a way, probably, removing the singletons or some other way. 

Regards,
Veera

**Comment by fgvieira** [comment]
Hi Veera,

it is working now.
thanks!
